### ISSUE TITLE
Brew Cask fails to install on first run of Boxen

### ISSUE THREAD

**Issue by jen20** [boxen/puppet-brewcask#36]
Upon running Boxen on a fresh installation of OS X, it seems that there's some version mismatch between the version of git that brew cask wants and the version that `puppet-git` installs. Running `brew install brew-cask` manually after the first run installs it and following that packages will install successfully using the `brewcask` provider which makes me suspect there's a version mismatch in this module somewhere. I'll try to investigate if no-one gets there first but flagging it up here for anyone else that happens to run into it.

The error log is as follows:

```
Error: Execution of 'brew boxen-install brew-cask' returned 1: ==> Installing brew-cask from caskroom/homebrew-cask
==> Installing brew-cask dependency: git
Warning: Building source; cellar of git's bottle is /usr/local/Cellar
==> Downloading https://www.kernel.org/pub/software/scm/git/git-2.3.0.tar.gz
==> make prefix=/opt/boxen/homebrew/Cellar/git/2.3.0 sysconfdir=/opt/boxen/homebrew/etc CC=clang CFLAGS= LDFLAGS= install
CURLOPT_SSL_OPTIONS
^
1 error generated.
make: *** [imap-send.o] Error 1
make: *** Waiting for unfinished jobs....

READ THIS: http://git.io/brew-troubleshooting

These open issues may also help:
Add versioned git-hooks (https://github.com/Homebrew/homebrew/pull/36236)
Homebrew installation failed: fatal: Could not switch to '.git': Permission denied Failed during: git init -q (https://github.com/Homebrew/homebrew/issues/36504)
git-big-picture: new formula v0.9.0 (https://github.com/Homebrew/homebrew/pull/36812)
git-flow-clone has stopped working... (https://github.com/Homebrew/homebrew/issues/32701)
Error: /Stage[main]/Brewcask/Package[brew-cask]/ensure: change from absent to present failed: Execution of 'brew boxen-install brew-cask' returned 1: ==> Installing brew-cask from caskroom/homebrew-cask
==> Installing brew-cask dependency: git
Warning: Building source; cellar of git's bottle is /usr/local/Cellar
==> Downloading https://www.kernel.org/pub/software/scm/git/git-2.3.0.tar.gz
==> make prefix=/opt/boxen/homebrew/Cellar/git/2.3.0 sysconfdir=/opt/boxen/homebrew/etc CC=clang CFLAGS= LDFLAGS= install
CURLOPT_SSL_OPTIONS
^
1 error generated.
make: *** [imap-send.o] Error 1
make: *** Waiting for unfinished jobs....

READ THIS: http://git.io/brew-troubleshooting

These open issues may also help:
Add versioned git-hooks (https://github.com/Homebrew/homebrew/pull/36236)
Homebrew installation failed: fatal: Could not switch to '.git': Permission denied Failed during: git init -q (https://github.com/Homebrew/homebrew/issues/36504)
git-big-picture: new formula v0.9.0 (https://github.com/Homebrew/homebrew/pull/36812)
git-flow-clone has stopped working... (https://github.com/Homebrew/homebrew/issues/32701)
```

**Comment by radeksimko** [comment]
Hi James,
I remember I've seen this error before. I think it was on fresh Yosemite without any updates, only basic XCode CLI Tools. At least that's why I recently sent this PR: https://github.com/timsutton/osx-vm-templates/pull/28

What OS X version (full version in format X.Y.Z) are you running on + have you downloaded all available App Store updates for the system and related SW (XCode CLI Tools for instance)?

btw. even if it's a valid bug, it's not related to this module as the error happens during git installation which is why I'm closing this, but feel free to answer and/or open this issue elsewhere, it may help others facing the same issue.

**Comment by dgoodlad** [comment]
This is an ordering issue; the boxen/puppet-git module tries to install its own git, but is doing so after brew cask has installed homebrew's default version of git because it lies somewhere in its dependency chain.

This is definitely an issue with boxen/puppet-git, or more fundamentally with boxen/puppet-homebrew. @radeksimko is right, it's not directly a problem with this module. I'll open an issue on the other modules for tracking.
